apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: blue
spec:
  hostnames:
    - blue.gwapi.acelog.xyz
  parentRefs:
    - namespace: traefik
      name: traefik-gateway
  rules:
    - backendRefs:
        - name: blue
          port: 80
