apiVersion: v1
kind: LimitRange
metadata:
  name: my-very-detailed-limitrange
spec:
  limits:
  - type: Container
    default:
      cpu: 1
      memory: 100M
    defaultRequest:
      cpu: 0.1
      memory: 100M
