kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: blue
spec:
  podSelector:
    matchLabels:
      app: blue
  ingress:
  - from:
      - podSelector:
          matchLabels:
            app: rainbow

