apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-deployment
  labels:
    app: color
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color
  template:
    metadata:
      labels:
        app: color
    spec:
      containers:
      - name: color
        image: jpetazzo/color
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: color-service
spec:
  selector:
    app: color
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

