apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yellow
  name: yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow
  template:
    metadata:
      labels:
        app: yellow
    spec:
      containers:
      - image: jpetazzo/color
        name: color
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yellow
  name: yellow
spec:
  ports:
  - port: 80
  selector:
    app: yellow
