#@ name = "blue"
#@ image = "jpetazzo/color"
#@ port = 80
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #@ name
  name: #@ name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name
  template:
    metadata:
      labels:
        app: #@ name
    spec:
      containers:
      - image: #@ image
        name: #@ name
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: #@ name
  name: #@ name
spec:
  ports:
  - name: #@ name
    port: #@ port
  selector:
    app: #@ name
---
#@ name
