#@ name = "blue"
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: #@ name
  name: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: jpetazzo/color
        name: color
