---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: m3-generic/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: m3-flux-generic
  values:
    image:
      repository: redis
      tag: latest
    service:
      port: 6379
