---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  releaseName: redis
  chart:
    spec:
      chart: m3-generic/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: m3-flux-generic
  values:
    image:
      repository: redis
      tag: latest
    service:
      port: 6379
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hasher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: m3-generic/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: hasher
  targetNamespace: m3-flux-generic
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rng
  namespace: flux-system
spec:
  chart:
    spec:
      chart: m3-generic/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: rng
  targetNamespace: m3-flux-generic
  values: {}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: worker
  namespace: flux-system
spec:
  chart:
    spec:
      chart: m3-generic/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: worker
  targetNamespace: m3-flux-generic
  values:
    service: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webui
  namespace: flux-system
spec:
  chart:
    spec:
      chart: m3-generic/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: webui
  targetNamespace: m3-flux-generic
  values:
    service:
      type: NodePort
