---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-password
spec:
  encryptedData:
    password: AgCHLevxyobphUWTGx/w8B4QKm2C/x37gNADiQZiq3L0GDtA7C6pO1Pjs8D9/amhPmu3BW4N7RXFyPsuYHQPspPTbXqLjeXd8bSuohS6e4G6YwzOtxXUHlodGrv5+WTNY86+ujcT+SD50lQYTOW6+eB7zI4tY03IyhChzicmKmJL6BwdzUruBD31Ugvtbw9UouPiZVhZoGAIHaeQ8ouUothKFQ68fhcs8+nMOaKJlOiZPo5AVJbQUbkJ7Io4ymbk+7pUqW9snrUkj2wTBOTez5WUGNXm2CZsClXUOOFOihTcWyKWqY5e8gBNIkzEnwfJeMF8HUVqyM8NzoQZ3Lt6plmj9LlkJsR0//2SF5f7oKIyHJ7lJlexocrZJrzFHo8r36xMf7J2AFWsNu3FepRiqYBv/yTyEh4HDGVhfGqAuiz+gMOXU55uSyg0Yk2JwHiWV8B0vjBkS8jX/vydzWjXVjRWL2Oy0oyg7MW8b/elaeYiJ6+6nvM6DZ7WO1ZRygBtNVSsq75NHXCIrXLeSnTZN3f7cYDoFyiz2wbsHNNJI3skx9j9Z5Q0H18dv+1nJ2J48e1oZ6B5roS6cpd9sQrFg/Qgm+wCpoBR2MHE+zkvXf+urtRs+TDidCh1shnS6klIcw/kyoHkwK2wXP/1nN6jvF6p1ew1f9mflId4WxoUmcksSYs3OG/0UYVkRh7aXZvP8uEWLmFhe7SERjVMLt39J1XzDsaJCEs80gBnVrsJ
  template:
    metadata:
      creationTimestamp: null
      name: database-password
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: logging-api-token
spec:
  encryptedData:
    token: AgClzEKAGckEVGMiyxTK/s+aJ7SuO5I+FqVatvHEExVV+Vca0TVBDwFJW8cax1StPu72fmz3OkGuLpnLWNdA7rMZGYRd0Ikdl/l0k+Eb9bFeJGPiUnp5APMdkzz66uYB47E+zElIFbwBp+tTPW7dWA2j0VEfHnhHVEEHjQNhvgRQNWa1HVlNBEWomLfQJZz/ulPQOkFpIpMbGYajg2qCqO3v5TJCoXP14FPep3KP7GZTqHANStu4NaJwzfdAjFWvXliFlpdy5i0ihtraZ7Kncp6oyIyfRtJuPnFhS6ZfnKEG9B9IrvuaD5Bb/SaeKrVubeW2ylpYrNSnpZ57YevNAQsvfeCRbHLQv9unUWDVXUU1bFFDPPJjXDeS8Z+1U4pZ1G376PHBps96uEgvbqPeU6XVzeqbEa+iG2VpvQcm6HnuuAH6NOhnR3el0nMzq8FDanIFj5YLY9iANw6m9b7+l6YPLj6HxAa0f8XREURdthE4YbP4Di5KhoGwnnE8icwIbfMt3mer99e3g9tT1VgoKI5v+wgHkJzrtHwsWYgcgOSjgruV4zA2SUpR92+b7MaOHoBN4vEWp9NK0QBHdUu7rIQcYple7XkZrs+1ttOhMjspxxWHJr/aFBHS7/cmQSb3JNITHhiGvIFMH+sc+Kr3X++1fmoGRrETPPVKUSD4IAi3WgVePF7ttS8fwY6JWWXh8F5Npj+lPKMNDvaZPd0ssHfRdF6viAyE+g==
  template:
    metadata:
      creationTimestamp: null
      name: logging-api-token
