apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  externalName: redis.prod.svc.cluster.local
  selector:
    app: redis
  type: ExternalName
status:
  loadBalancer: {}
