apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pingpong
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      terminationGracePeriodSeconds: 3
      volumes:
      - name: conf
        configMap:
          name: pingpong
      containers:
      - command:
        - sh
        - -c
        - ping $TARGET
        image: alpine
        name: alpine
        volumeMounts:
        - name: conf
          mountPath: /etc/pingpong
        env:
        - name: TARGET
          valueFrom:
            configMapKeyRef:
              name: pingpong
              key: target
        - name: HELLO
          value: world
