apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: toto
  name: rs2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toto
  template:
    metadata:
      labels:
        app: toto
    spec:
      containers:
      - image: jpetazzo/color
        name: color
