apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alice
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: alice
