apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alice
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - bitnami.com
  resources:
  - sealedsecrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
  resourceNames:
  - logging-api-token
