apiVersion: v1
kind: LimitRange
metadata:
  namespace: kube-system
  name: kube-system
spec:
  limits:
  - type: Container
    default:
      cpu: 1
      memory: 100M
    defaultRequest:
      cpu: 0.1
      memory: 100M
