apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  externalName: dockercoins-redis-master.{{ .Release.Namespace }}.svc.cluster.local
  selector:
    app: redis
  type: ExternalName
